language: python

python:
  - "3.5"

sudo: false

services:
  - postgresql

install:
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database lostandfound;' -U postgres

script:
  - LOCAL_SETTINGS_FILE="local.base.cfg#test" python manage.py test
