language: python

python:
  - "3.3"
  - "3.4"

sudo: false

addons:
    - postgresql: "9.4"

install:
    - pip install -r requirements.txt

script:
    - LOCAL_SETTINGS_FILE="local.base.cfg#test" python manage.py test
