language: python
python:
  - "3.3"
sudo: false
# command to install dependencies
install:
  - cp variables.travis.py variables.py
  - |
    make init <<<"Joe
    Doe
    joe@example.com
    joe
    "
# command to run tests
script: make test
# Spam the IRC channel yay!
notifications:
  irc: "irc.cat.pdx.edu#arc"
